
/* ## ALUGUE SERVICE ##
ALUNOS: ANTONIO PAULO WINTER JUNIOR
        VINICIUS WASHINGTON NICHALS FILHO
        UILIAN GUSTAVO DE FREITAS LOURENÇO */

  CREATE TABLE TBL_CLIENTE (
  ID_CLIENTE INTEGER PRIMARY KEY NOT NULL,
  NOME_CLIENTE VARCHAR2(60) NOT NULL,
  SOBRENOME_CLIENTE VARCHAR2(60) NOT NULL,
  TELEFONE_CLIENTE VARCHAR2(60) NULL,
  CELULAR_CLIENTE VARCHAR2(60) NOT NULL,
  CPF_CLIENTE VARCHAR2(60) NOT NULL,
  RUA_CLIENTE VARCHAR2(60) NOT NULL,
  BAIRRO_CLIENTE VARCHAR2(60) NOT NULL,
  NUMERO_CLIENTE VARCHAR2(10) NOT NULL,
  CIDADE_CLIENTE VARCHAR2(60) NOT NULL,
  CEP_CLIENTE VARCHAR2(15) NULL,
  STATUS_CLIENTE NUMBER(1) NOT NULL --0 INATIVO | 1 ATIVO 
  );
  
    CREATE SEQUENCE ID_CLIENTE
INCREMENT BY 1
START WITH 1
NOCACHE;

----------------------------------------------------

CREATE TABLE TBL_OPERADOR (
  ID_OPERADOR INTEGER PRIMARY KEY NOT NULL,
  NOME_OPERADOR VARCHAR2(60) NOT NULL,
  SOBRENOME_OPERADOR VARCHAR2(60) NOT NULL,
  SENHA_OPERADOR VARCHAR2(20) NOT NULL,
  STATUS_OPERADOR NUMBER(1)  NOT NULL, --0 INATIVO | 1 ATIVO 
  NIVEL_OPERADOR NUMBER(1)  NOT NULL, --DEFINIR SE É ADMINISTRADOR OU ATENDENTE | --1 ADM | 2 ATENDENTE
  CPF_OPERADOR VARCHAR2(20) NOT NULL,
  TELEFONE_OPERADOR VARCHAR2(20) NOT NULL,
  CELULAR_OPERADOR VARCHAR2(20) NOT NULL,
  RUA_OPERADOR VARCHAR2(60) NOT NULL,
  BAIRRO_OPERADOR VARCHAR2(60) NOT NULL,
  NUMERO_OPERADOR VARCHAR2(10) NOT NULL,
  CIDADE_OPERADOR VARCHAR2(60) NOT NULL,
  CEP_OPERADOR VARCHAR2(15) NOT NULL
 );

     CREATE SEQUENCE ID_OPERADOR
INCREMENT BY 1
START WITH 1
NOCACHE;
 
---------------------------------------------------- 

CREATE TABLE TBL_PRODUTO (
  ID_PRODUTO INTEGER PRIMARY KEY NOT NULL,
  VALOR_PRODUTO FLOAT NOT NULL,
  STATUS_PRODUTO NUMBER(1)  NOT NULL, -- 0 INATIVO | 1 ATIVO | 2 ALUGADO
  NOME_PRODUTO VARCHAR2(60) NOT NULL,
  DESCRICAO_PRODUTO VARCHAR2(1000) NULL,
  TAMANHO_PRODUTO VARCHAR2(20) NOT NULL,
  GENERO_PRODUTO VARCHAR2(1) NOT NULL
  );

     CREATE SEQUENCE ID_PRODUTO
INCREMENT BY 1
START WITH 1
NOCACHE;

----------------------------------------------------

CREATE TABLE TBL_CUPOM (
  ID_CUPOM INTEGER PRIMARY KEY NOT NULL,
  ID_CLIENTE INTEGER NOT NULL,
  DATA_INCLUSAO DATE NOT NULL,
  ID_OPERADOR INTEGER NOT NULL,
  STATUS_CUPOM NUMBER(1)  NOT NULL, -- 0 INATIVO | 1 ATIVO 
  VALOR_CUPOM FLOAT NOT NULL 
  );
  
       CREATE SEQUENCE ID_CUPOM
INCREMENT BY 1
START WITH 1
NOCACHE;

----------------------------------------------------

CREATE TABLE TBL_ALUGUEL (
  ID_ALUGUEL INTEGER PRIMARY KEY NOT NULL,
  ID_CLIENTE INTEGER NOT NULL,
  ID_OPERADOR INTEGER NOT NULL,
  ID_CONF INTEGER NOT NULL,
  ID_CUPOM INTEGER NULL,
  DATA_ALUGUEL DATE NOT NULL,
  DATA_PREVISTA DATE NOT NULL,
  DATA_ENTREGA DATE NULL,
  STATUS_ALUGUEL INTEGER NOT NULL, -- 0 CANCELADO | 1 ATIVO | 2 FINALIZADO
  QUANTIDADE_MULTA INTEGER NULL,
  VALOR_ALUGUEL FLOAT NOT NULL,
  VALOR_MULTA FLOAT NULL,
  VALOR_TOTAL FLOAT NULL
  );
  
       CREATE SEQUENCE ID_ALUGUEL
INCREMENT BY 1
START WITH 1
NOCACHE;

----------------------------------------------------
  
  CREATE TABLE TBL_CONFIGURACOES (
  ID_CONF INTEGER PRIMARY KEY NOT NULL,
  MULTA_VALOR FLOAT NOT NULL,
  CUPOM_VALOR FLOAT NOT NULL
  );
  
    CREATE SEQUENCE ID_CONF
INCREMENT BY 1
START WITH 1
NOCACHE;

----------------------------------------------------

CREATE TABLE TBL_PRODUTOS_ALUGUEL (
  ID_ALUGUEL INTEGER NOT NULL,
  ID_PRODUTO INTEGER NOT NULL,
  VALOR_PRODUTO_ALUGUEL FLOAT NOT NULL,
  NOME_PRODUTO_ALUGUEL VARCHAR2(60) NOT NULL,
  DESCRICAO_PRODUTO_ALUGUEL VARCHAR2(1000) NULL,
  TAMANHO_PRODUTO_ALUGUEL VARCHAR2(20) NOT NULL,
  GENERO_PRODUTO_ALUGUEL VARCHAR2(1) NOT NULL
);

----------------------------------------------------

ALTER TABLE TBL_ALUGUEL ADD CONSTRAINT FK_ALUGUEL_OPERADOR FOREIGN KEY (ID_OPERADOR) REFERENCES TBL_OPERADOR(ID_OPERADOR);
ALTER TABLE TBL_ALUGUEL ADD CONSTRAINT FK_ALUGUEL_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES TBL_CLIENTE(ID_CLIENTE);
ALTER TABLE TBL_ALUGUEL ADD CONSTRAINT FK_ALUGUEL_CONFIGURACAO FOREIGN KEY (ID_CONF) REFERENCES TBL_CONFIGURACOES(ID_CONF);
ALTER TABLE TBL_ALUGUEL ADD CONSTRAINT FK_ALUGUEL_CUPOM FOREIGN KEY (ID_CUPOM) REFERENCES TBL_CUPOM(ID_CUPOM);

----------------------------------------------------

ALTER TABLE TBL_PRODUTOS_ALUGUEL ADD CONSTRAINT FK_ALUGUEL_PRODUTO FOREIGN KEY (ID_ALUGUEL) REFERENCES TBL_ALUGUEL(ID_ALUGUEL);
ALTER TABLE TBL_PRODUTOS_ALUGUEL ADD CONSTRAINT FK_PRODUTO_ALUGUEL FOREIGN KEY (ID_PRODUTO) REFERENCES TBL_PRODUTO(ID_PRODUTO);
ALTER TABLE TBL_PRODUTOS_ALUGUEL ADD PRIMARY KEY (ID_ALUGUEL,ID_PRODUTO);


----------------------------------------------------

INSERT INTO TBL_CLIENTE (ID_CLIENTE,NOME_CLIENTE,SOBRENOME_CLIENTE,TELEFONE_CLIENTE,CELULAR_CLIENTE,CPF_CLIENTE,RUA_CLIENTE,BAIRRO_CLIENTE,NUMERO_CLIENTE,CIDADE_CLIENTE,CEP_CLIENTE,STATUS_CLIENTE) VALUES (ID_CLIENTE.NEXTVAL,'José','Silva','(41)1111-1111','(41)2222-2222','123.123.123-12','Rua das flores',' Bairro da floresta','123a','Curitiba','11111-111',1);
INSERT INTO TBL_CLIENTE (ID_CLIENTE,NOME_CLIENTE,SOBRENOME_CLIENTE,TELEFONE_CLIENTE,CELULAR_CLIENTE,CPF_CLIENTE,RUA_CLIENTE,BAIRRO_CLIENTE,NUMERO_CLIENTE,CIDADE_CLIENTE,CEP_CLIENTE,STATUS_CLIENTE) VALUES (ID_CLIENTE.NEXTVAL,'João','Maria','(41)3333-3333','(41)4444-4444','321.321.321-32','Rua das árvores',' Bairro da mata','1600','Curitiba','22222-222',1); 
INSERT INTO TBL_CLIENTE (ID_CLIENTE,NOME_CLIENTE,SOBRENOME_CLIENTE,TELEFONE_CLIENTE,CELULAR_CLIENTE,CPF_CLIENTE,RUA_CLIENTE,BAIRRO_CLIENTE,NUMERO_CLIENTE,CIDADE_CLIENTE,CEP_CLIENTE,STATUS_CLIENTE) VALUES (ID_CLIENTE.NEXTVAL,'Miguel','Savage','(38)2622-2447','(81)9670-2594','443.770.666-11','Rua Pinus','Mata','353','Almirante Tamandaré','29468-065',1);
INSERT INTO TBL_CLIENTE (ID_CLIENTE,NOME_CLIENTE,SOBRENOME_CLIENTE,TELEFONE_CLIENTE,CELULAR_CLIENTE,CPF_CLIENTE,RUA_CLIENTE,BAIRRO_CLIENTE,NUMERO_CLIENTE,CIDADE_CLIENTE,CEP_CLIENTE,STATUS_CLIENTE) VALUES (ID_CLIENTE.NEXTVAL,'Davi','Franklin','(74)2496-2137','(93)5590-1414','864.063.142-38','Rua Pinheiro','Mato','262','Balsa Nova','45244-439',1);
INSERT INTO TBL_CLIENTE (ID_CLIENTE,NOME_CLIENTE,SOBRENOME_CLIENTE,TELEFONE_CLIENTE,CELULAR_CLIENTE,CPF_CLIENTE,RUA_CLIENTE,BAIRRO_CLIENTE,NUMERO_CLIENTE,CIDADE_CLIENTE,CEP_CLIENTE,STATUS_CLIENTE) VALUES (ID_CLIENTE.NEXTVAL,'Arthur','Duke','(57)7220-0421','(66)7068-0287','106.337.854-51','Rua Chorão','Centro','935','Colombo','32617-929',1);
INSERT INTO TBL_CLIENTE (ID_CLIENTE,NOME_CLIENTE,SOBRENOME_CLIENTE,TELEFONE_CLIENTE,CELULAR_CLIENTE,CPF_CLIENTE,RUA_CLIENTE,BAIRRO_CLIENTE,NUMERO_CLIENTE,CIDADE_CLIENTE,CEP_CLIENTE,STATUS_CLIENTE) VALUES (ID_CLIENTE.NEXTVAL,'Alice','Joyce','(17)5726-7340','(99)7021-6372','234.099.086-38','Rua Cerejeira','Centro','46','Pinhais','20743-076',1);
INSERT INTO TBL_CLIENTE (ID_CLIENTE,NOME_CLIENTE,SOBRENOME_CLIENTE,TELEFONE_CLIENTE,CELULAR_CLIENTE,CPF_CLIENTE,RUA_CLIENTE,BAIRRO_CLIENTE,NUMERO_CLIENTE,CIDADE_CLIENTE,CEP_CLIENTE,STATUS_CLIENTE) VALUES (ID_CLIENTE.NEXTVAL,'Isabella','Davis','(83)2786-4300','(72)9344-2223','382.021.133-99','Rua arbusto','Centro','414','Campo Largo','93441-270',1);
INSERT INTO TBL_CLIENTE (ID_CLIENTE,NOME_CLIENTE,SOBRENOME_CLIENTE,TELEFONE_CLIENTE,CELULAR_CLIENTE,CPF_CLIENTE,RUA_CLIENTE,BAIRRO_CLIENTE,NUMERO_CLIENTE,CIDADE_CLIENTE,CEP_CLIENTE,STATUS_CLIENTE) VALUES (ID_CLIENTE.NEXTVAL,'Laura','Murray','(73)6408-5308','(37)1788-4297','241.220.117-82','Rua do trigo','Centro','175','Campo Largo','32255-169',1);
INSERT INTO TBL_CLIENTE (ID_CLIENTE,NOME_CLIENTE,SOBRENOME_CLIENTE,TELEFONE_CLIENTE,CELULAR_CLIENTE,CPF_CLIENTE,RUA_CLIENTE,BAIRRO_CLIENTE,NUMERO_CLIENTE,CIDADE_CLIENTE,CEP_CLIENTE,STATUS_CLIENTE) VALUES (ID_CLIENTE.NEXTVAL,'Luciano','Solomon','(89)5266-6407','(49)4601-7944','885.246.468-57','Rua das pedras','Centro','136','Lapa','11568-814',1);
INSERT INTO TBL_CLIENTE (ID_CLIENTE,NOME_CLIENTE,SOBRENOME_CLIENTE,TELEFONE_CLIENTE,CELULAR_CLIENTE,CPF_CLIENTE,RUA_CLIENTE,BAIRRO_CLIENTE,NUMERO_CLIENTE,CIDADE_CLIENTE,CEP_CLIENTE,STATUS_CLIENTE) VALUES (ID_CLIENTE.NEXTVAL,'Rafael','Wilkins','(34)7901-0286','(87)8075-8683','684.569.024-75','Rua dos caminhos','Centro','605','Balsa Nova','22606-305',1);
INSERT INTO TBL_CLIENTE (ID_CLIENTE,NOME_CLIENTE,SOBRENOME_CLIENTE,TELEFONE_CLIENTE,CELULAR_CLIENTE,CPF_CLIENTE,RUA_CLIENTE,BAIRRO_CLIENTE,NUMERO_CLIENTE,CIDADE_CLIENTE,CEP_CLIENTE,STATUS_CLIENTE) VALUES (ID_CLIENTE.NEXTVAL,'Gustavo','Anderson','(48)9262-7556','(95)4419-1666','458.212.961-41','Rua laranjeira','Centro','357','Curitiba','33478-268',1);
INSERT INTO TBL_CLIENTE (ID_CLIENTE,NOME_CLIENTE,SOBRENOME_CLIENTE,TELEFONE_CLIENTE,CELULAR_CLIENTE,CPF_CLIENTE,RUA_CLIENTE,BAIRRO_CLIENTE,NUMERO_CLIENTE,CIDADE_CLIENTE,CEP_CLIENTE,STATUS_CLIENTE) VALUES (ID_CLIENTE.NEXTVAL,'Lara','Forbes','(79)8611-7004','(18)7980-4422','967.322.551-50','Avenida pinheirão','Centro','266','Tijucas do Sul','38774-092',1);
INSERT INTO TBL_CLIENTE (ID_CLIENTE,NOME_CLIENTE,SOBRENOME_CLIENTE,TELEFONE_CLIENTE,CELULAR_CLIENTE,CPF_CLIENTE,RUA_CLIENTE,BAIRRO_CLIENTE,NUMERO_CLIENTE,CIDADE_CLIENTE,CEP_CLIENTE,STATUS_CLIENTE) VALUES (ID_CLIENTE.NEXTVAL,'Rafaela','Carney','(82)6922-1416','(68)1479-6841','845.210.277-06','Alameda dos anjos','Centro','772','Balsa Nova','83851-782',1);
INSERT INTO TBL_CLIENTE (ID_CLIENTE,NOME_CLIENTE,SOBRENOME_CLIENTE,TELEFONE_CLIENTE,CELULAR_CLIENTE,CPF_CLIENTE,RUA_CLIENTE,BAIRRO_CLIENTE,NUMERO_CLIENTE,CIDADE_CLIENTE,CEP_CLIENTE,STATUS_CLIENTE) VALUES (ID_CLIENTE.NEXTVAL,'Lorena','Schultz','(42)3723-8229','(20)1167-1338','523.469.161-15','Rua rayovac','Centro','201','Campo do Tenente','97282-583',1);
INSERT INTO TBL_CLIENTE (ID_CLIENTE,NOME_CLIENTE,SOBRENOME_CLIENTE,TELEFONE_CLIENTE,CELULAR_CLIENTE,CPF_CLIENTE,RUA_CLIENTE,BAIRRO_CLIENTE,NUMERO_CLIENTE,CIDADE_CLIENTE,CEP_CLIENTE,STATUS_CLIENTE) VALUES (ID_CLIENTE.NEXTVAL,'Letícia','Maynard','(64)3254-6316','(78)2024-2538','623.414.424-28','Rua araça','Centro','541','Curitiba','73396-033',1);
INSERT INTO TBL_CLIENTE (ID_CLIENTE,NOME_CLIENTE,SOBRENOME_CLIENTE,TELEFONE_CLIENTE,CELULAR_CLIENTE,CPF_CLIENTE,RUA_CLIENTE,BAIRRO_CLIENTE,NUMERO_CLIENTE,CIDADE_CLIENTE,CEP_CLIENTE,STATUS_CLIENTE) VALUES (ID_CLIENTE.NEXTVAL,'Isaac','Meyer','(37)4467-2921','(30)4585-9256','204.080.121-46','Rua amoreira','Centro','600','Piên','14526-146',1);
INSERT INTO TBL_CLIENTE (ID_CLIENTE,NOME_CLIENTE,SOBRENOME_CLIENTE,TELEFONE_CLIENTE,CELULAR_CLIENTE,CPF_CLIENTE,RUA_CLIENTE,BAIRRO_CLIENTE,NUMERO_CLIENTE,CIDADE_CLIENTE,CEP_CLIENTE,STATUS_CLIENTE) VALUES (ID_CLIENTE.NEXTVAL,'Vinicius','Baker','(69)3017-7877','(70)9705-8863','704.521.285-91','Rua araribá','Centro','23','Doutor Ulysses','38566-658',1);
INSERT INTO TBL_CLIENTE (ID_CLIENTE,NOME_CLIENTE,SOBRENOME_CLIENTE,TELEFONE_CLIENTE,CELULAR_CLIENTE,CPF_CLIENTE,RUA_CLIENTE,BAIRRO_CLIENTE,NUMERO_CLIENTE,CIDADE_CLIENTE,CEP_CLIENTE,STATUS_CLIENTE) VALUES (ID_CLIENTE.NEXTVAL,'Joaquim','Downs','(67)9044-8729','(63)8844-6975','517.156.946-31','Rua cajazeira','Centro','780','Quitandinha','11955-642',1);
INSERT INTO TBL_CLIENTE (ID_CLIENTE,NOME_CLIENTE,SOBRENOME_CLIENTE,TELEFONE_CLIENTE,CELULAR_CLIENTE,CPF_CLIENTE,RUA_CLIENTE,BAIRRO_CLIENTE,NUMERO_CLIENTE,CIDADE_CLIENTE,CEP_CLIENTE,STATUS_CLIENTE) VALUES (ID_CLIENTE.NEXTVAL,'Lavínia','Ferguson','(60)1926-9742','(24)1542-4953','511.424.372-79','Rua do castanheiro','Centro','742','Agudos do Sul','27452-674',1);
INSERT INTO TBL_CLIENTE (ID_CLIENTE,NOME_CLIENTE,SOBRENOME_CLIENTE,TELEFONE_CLIENTE,CELULAR_CLIENTE,CPF_CLIENTE,RUA_CLIENTE,BAIRRO_CLIENTE,NUMERO_CLIENTE,CIDADE_CLIENTE,CEP_CLIENTE,STATUS_CLIENTE) VALUES (ID_CLIENTE.NEXTVAL,'Carlos','Booth','(66)3800-5243','(74)8275-3884','187.974.812-01','Rua do ébano','Centro','321','Piên','98233-586',1);
INSERT INTO TBL_CLIENTE (ID_CLIENTE,NOME_CLIENTE,SOBRENOME_CLIENTE,TELEFONE_CLIENTE,CELULAR_CLIENTE,CPF_CLIENTE,RUA_CLIENTE,BAIRRO_CLIENTE,NUMERO_CLIENTE,CIDADE_CLIENTE,CEP_CLIENTE,STATUS_CLIENTE) VALUES (ID_CLIENTE.NEXTVAL,'Bianca','Mueller','(53)1451-8147','(49)1053-6212','385.035.986-82','Rua eucalipto','Centro','933','Adrianópolis','21942-917',1);
INSERT INTO TBL_CLIENTE (ID_CLIENTE,NOME_CLIENTE,SOBRENOME_CLIENTE,TELEFONE_CLIENTE,CELULAR_CLIENTE,CPF_CLIENTE,RUA_CLIENTE,BAIRRO_CLIENTE,NUMERO_CLIENTE,CIDADE_CLIENTE,CEP_CLIENTE,STATUS_CLIENTE) VALUES (ID_CLIENTE.NEXTVAL,'Elvis','Simpson','(57)7731-8583','(67)7568-5496','964.459.060-80','Rua goiabeira','Centro','321','Piên','49624-974',1);


----------------------------------------------------
 
INSERT INTO TBL_OPERADOR (ID_OPERADOR,NOME_OPERADOR,SOBRENOME_OPERADOR,SENHA_OPERADOR,STATUS_OPERADOR,NIVEL_OPERADOR,CPF_OPERADOR,TELEFONE_OPERADOR,CELULAR_OPERADOR,RUA_OPERADOR,BAIRRO_OPERADOR,NUMERO_OPERADOR,CIDADE_OPERADOR,CEP_OPERADOR) VALUES (ID_OPERADOR.NEXTVAL,'ADMINISTRADOR','Adm','admin',1,1,'111.111.111-11','(11)1111-1111','(11)1111-1111','ADMINISTRADOR','ADMINISTRADOR','1','Curitiba','11111-111');
INSERT INTO TBL_OPERADOR (ID_OPERADOR,NOME_OPERADOR,SOBRENOME_OPERADOR,SENHA_OPERADOR,STATUS_OPERADOR,NIVEL_OPERADOR,CPF_OPERADOR,TELEFONE_OPERADOR,CELULAR_OPERADOR,RUA_OPERADOR,BAIRRO_OPERADOR,NUMERO_OPERADOR,CIDADE_OPERADOR,CEP_OPERADOR) VALUES (ID_OPERADOR.NEXTVAL,'ATENDENTE','Atnd','senha123',1,2,'222.222.222-22','(33)3333-3333','(44)4444-4444','ATENDENTE','ATENDENTE','2','Curitiba','22222-222');
INSERT INTO TBL_OPERADOR (ID_OPERADOR,NOME_OPERADOR,SOBRENOME_OPERADOR,SENHA_OPERADOR,STATUS_OPERADOR,NIVEL_OPERADOR,CPF_OPERADOR,TELEFONE_OPERADOR,CELULAR_OPERADOR,RUA_OPERADOR,BAIRRO_OPERADOR,NUMERO_OPERADOR,CIDADE_OPERADOR,CEP_OPERADOR) VALUES (ID_OPERADOR.NEXTVAL,'UILIAN','Gustavo','senha123',1,1,'489.894.565-40','(35)3603-1273','(56)3245-2440','Rua','Boa Vista','239','Campo do Tenente','21032-938');
INSERT INTO TBL_OPERADOR (ID_OPERADOR,NOME_OPERADOR,SOBRENOME_OPERADOR,SENHA_OPERADOR,STATUS_OPERADOR,NIVEL_OPERADOR,CPF_OPERADOR,TELEFONE_OPERADOR,CELULAR_OPERADOR,RUA_OPERADOR,BAIRRO_OPERADOR,NUMERO_OPERADOR,CIDADE_OPERADOR,CEP_OPERADOR) VALUES (ID_OPERADOR.NEXTVAL,'MARCOS','Lira','senha123',1,1,'381.560.133-30','(73)9435-3471','(40)6346-0058','Rua','Boqueirão','855','Lapa','29858-671');
INSERT INTO TBL_OPERADOR (ID_OPERADOR,NOME_OPERADOR,SOBRENOME_OPERADOR,SENHA_OPERADOR,STATUS_OPERADOR,NIVEL_OPERADOR,CPF_OPERADOR,TELEFONE_OPERADOR,CELULAR_OPERADOR,RUA_OPERADOR,BAIRRO_OPERADOR,NUMERO_OPERADOR,CIDADE_OPERADOR,CEP_OPERADOR) VALUES (ID_OPERADOR.NEXTVAL,'CHUPIN','Albuquerque','senha123',1,1,'768.830.933-35','(36)6010-7214','(52)6978-9143','Rua','Tarumã','816','Rio Branco do Sul','06657-177');
INSERT INTO TBL_OPERADOR (ID_OPERADOR,NOME_OPERADOR,SOBRENOME_OPERADOR,SENHA_OPERADOR,STATUS_OPERADOR,NIVEL_OPERADOR,CPF_OPERADOR,TELEFONE_OPERADOR,CELULAR_OPERADOR,RUA_OPERADOR,BAIRRO_OPERADOR,NUMERO_OPERADOR,CIDADE_OPERADOR,CEP_OPERADOR) VALUES (ID_OPERADOR.NEXTVAL,'AUGUSTO','Busato','senha123',1,1,'395.723.620-52','(59)9575-4563','(72)2375-6476','Rua','Pilarzinho','56','Campo Magro','01166-844');
INSERT INTO TBL_OPERADOR (ID_OPERADOR,NOME_OPERADOR,SOBRENOME_OPERADOR,SENHA_OPERADOR,STATUS_OPERADOR,NIVEL_OPERADOR,CPF_OPERADOR,TELEFONE_OPERADOR,CELULAR_OPERADOR,RUA_OPERADOR,BAIRRO_OPERADOR,NUMERO_OPERADOR,CIDADE_OPERADOR,CEP_OPERADOR) VALUES (ID_OPERADOR.NEXTVAL,'ANDRÉ','Bird','senha123',1,1,'463.413.448-86','(13)2683-5379','(88)9578-0819','Rua','Pinheirinho','142','Quatro Barras','75716-507');
INSERT INTO TBL_OPERADOR (ID_OPERADOR,NOME_OPERADOR,SOBRENOME_OPERADOR,SENHA_OPERADOR,STATUS_OPERADOR,NIVEL_OPERADOR,CPF_OPERADOR,TELEFONE_OPERADOR,CELULAR_OPERADOR,RUA_OPERADOR,BAIRRO_OPERADOR,NUMERO_OPERADOR,CIDADE_OPERADOR,CEP_OPERADOR) VALUES (ID_OPERADOR.NEXTVAL,'CHARMANDER','Leonardo','senha123',1,1,'427.364.760-87','(87)1802-6737','(82)0633-3491','Rua','Portão','877','Balsa Nova','36740-685');
INSERT INTO TBL_OPERADOR (ID_OPERADOR,NOME_OPERADOR,SOBRENOME_OPERADOR,SENHA_OPERADOR,STATUS_OPERADOR,NIVEL_OPERADOR,CPF_OPERADOR,TELEFONE_OPERADOR,CELULAR_OPERADOR,RUA_OPERADOR,BAIRRO_OPERADOR,NUMERO_OPERADOR,CIDADE_OPERADOR,CEP_OPERADOR) VALUES (ID_OPERADOR.NEXTVAL,'CELSO','maia','Senha123',1,1,'434.842.783-40','(32)1078-1228','(82)6405-2008','Rua','Cajuru','645','Quatro Barras','34590-737');
INSERT INTO TBL_OPERADOR (ID_OPERADOR,NOME_OPERADOR,SOBRENOME_OPERADOR,SENHA_OPERADOR,STATUS_OPERADOR,NIVEL_OPERADOR,CPF_OPERADOR,TELEFONE_OPERADOR,CELULAR_OPERADOR,RUA_OPERADOR,BAIRRO_OPERADOR,NUMERO_OPERADOR,CIDADE_OPERADOR,CEP_OPERADOR) VALUES (ID_OPERADOR.NEXTVAL,'GERALDINHO','Clementino','senha123',1,1,'517.394.554-24','(46)1340-1950','(68)7594-0895','Rua','Hauer','264','Agudos do Sul','34226-451');
INSERT INTO TBL_OPERADOR (ID_OPERADOR,NOME_OPERADOR,SOBRENOME_OPERADOR,SENHA_OPERADOR,STATUS_OPERADOR,NIVEL_OPERADOR,CPF_OPERADOR,TELEFONE_OPERADOR,CELULAR_OPERADOR,RUA_OPERADOR,BAIRRO_OPERADOR,NUMERO_OPERADOR,CIDADE_OPERADOR,CEP_OPERADOR) VALUES (ID_OPERADOR.NEXTVAL,'XUXA','Guiera','senha123',1,1,'818.197.431-10','(52)2437-2780','(24)1402-1773','Rua','Centro','386','Lapa','54937-179');
INSERT INTO TBL_OPERADOR (ID_OPERADOR,NOME_OPERADOR,SOBRENOME_OPERADOR,SENHA_OPERADOR,STATUS_OPERADOR,NIVEL_OPERADOR,CPF_OPERADOR,TELEFONE_OPERADOR,CELULAR_OPERADOR,RUA_OPERADOR,BAIRRO_OPERADOR,NUMERO_OPERADOR,CIDADE_OPERADOR,CEP_OPERADOR) VALUES (ID_OPERADOR.NEXTVAL,'LULA','Roussef','senha123',1,1,'445.313.997-62','(81)5363-5114','(50)7175-1399','Rua','Boa Vista','278','Piên','48257-963');

---------------------------------------------------- 
INSERT INTO TBL_PRODUTO (ID_PRODUTO,VALOR_PRODUTO,STATUS_PRODUTO,NOME_PRODUTO,DESCRICAO_PRODUTO,TAMANHO_PRODUTO,GENERO_PRODUTO) VALUES (ID_PRODUTO.NEXTVAL,60.00,1,'Terno preto','Terno preto simples','G','M');
INSERT INTO TBL_PRODUTO (ID_PRODUTO,VALOR_PRODUTO,STATUS_PRODUTO,NOME_PRODUTO,DESCRICAO_PRODUTO,TAMANHO_PRODUTO,GENERO_PRODUTO) VALUES (ID_PRODUTO.NEXTVAL,80.00,1,'Vestido vermelho','Vestido vermelho com renda','ÚNICO','F');
INSERT INTO TBL_PRODUTO (ID_PRODUTO,VALOR_PRODUTO,STATUS_PRODUTO,NOME_PRODUTO,DESCRICAO_PRODUTO,TAMANHO_PRODUTO,GENERO_PRODUTO) VALUES (ID_PRODUTO.NEXTVAL,46.50,1,'Terno azul','Sem descrição','G','M');
INSERT INTO TBL_PRODUTO (ID_PRODUTO,VALOR_PRODUTO,STATUS_PRODUTO,NOME_PRODUTO,DESCRICAO_PRODUTO,TAMANHO_PRODUTO,GENERO_PRODUTO) VALUES (ID_PRODUTO.NEXTVAL,96.10,1,'Terno amarelo','Terno amarelo do maskara','PP','M');
INSERT INTO TBL_PRODUTO (ID_PRODUTO,VALOR_PRODUTO,STATUS_PRODUTO,NOME_PRODUTO,DESCRICAO_PRODUTO,TAMANHO_PRODUTO,GENERO_PRODUTO) VALUES (ID_PRODUTO.NEXTVAL,36.10,1,'Vestido amarelo','Descrição','GG','F');
INSERT INTO TBL_PRODUTO (ID_PRODUTO,VALOR_PRODUTO,STATUS_PRODUTO,NOME_PRODUTO,DESCRICAO_PRODUTO,TAMANHO_PRODUTO,GENERO_PRODUTO) VALUES (ID_PRODUTO.NEXTVAL,24.60,1,'Vestido azul','Descrição','M','F');
INSERT INTO TBL_PRODUTO (ID_PRODUTO,VALOR_PRODUTO,STATUS_PRODUTO,NOME_PRODUTO,DESCRICAO_PRODUTO,TAMANHO_PRODUTO,GENERO_PRODUTO) VALUES (ID_PRODUTO.NEXTVAL,97.90,1,'Vestido branco','Vestido de noiva','M','F');
INSERT INTO TBL_PRODUTO (ID_PRODUTO,VALOR_PRODUTO,STATUS_PRODUTO,NOME_PRODUTO,DESCRICAO_PRODUTO,TAMANHO_PRODUTO,GENERO_PRODUTO) VALUES (ID_PRODUTO.NEXTVAL,15.80,1,'Terno preto noivo','Terno preto de noivo, com colete prata','GG','M');
INSERT INTO TBL_PRODUTO (ID_PRODUTO,VALOR_PRODUTO,STATUS_PRODUTO,NOME_PRODUTO,DESCRICAO_PRODUTO,TAMANHO_PRODUTO,GENERO_PRODUTO) VALUES (ID_PRODUTO.NEXTVAL,55.10,1,'Terno prata','Terno prata','GG','M');
INSERT INTO TBL_PRODUTO (ID_PRODUTO,VALOR_PRODUTO,STATUS_PRODUTO,NOME_PRODUTO,DESCRICAO_PRODUTO,TAMANHO_PRODUTO,GENERO_PRODUTO) VALUES (ID_PRODUTO.NEXTVAL,65.00,1,'Terno preto','Terno preto simples','PP','M');
INSERT INTO TBL_PRODUTO (ID_PRODUTO,VALOR_PRODUTO,STATUS_PRODUTO,NOME_PRODUTO,DESCRICAO_PRODUTO,TAMANHO_PRODUTO,GENERO_PRODUTO) VALUES (ID_PRODUTO.NEXTVAL,12.80,1,'Vestido rosa','Sem descrição','PP','F');
INSERT INTO TBL_PRODUTO (ID_PRODUTO,VALOR_PRODUTO,STATUS_PRODUTO,NOME_PRODUTO,DESCRICAO_PRODUTO,TAMANHO_PRODUTO,GENERO_PRODUTO) VALUES (ID_PRODUTO.NEXTVAL,79.90,1,'Vestido lilás','Sem descrição','GG','F');
INSERT INTO TBL_PRODUTO (ID_PRODUTO,VALOR_PRODUTO,STATUS_PRODUTO,NOME_PRODUTO,DESCRICAO_PRODUTO,TAMANHO_PRODUTO,GENERO_PRODUTO) VALUES (ID_PRODUTO.NEXTVAL,84.50,1,'Terno vermelho','Sem descrição','M','M');
INSERT INTO TBL_PRODUTO (ID_PRODUTO,VALOR_PRODUTO,STATUS_PRODUTO,NOME_PRODUTO,DESCRICAO_PRODUTO,TAMANHO_PRODUTO,GENERO_PRODUTO) VALUES (ID_PRODUTO.NEXTVAL,84.00,1,'Vestido preto','Sem descrição','PP','F');
INSERT INTO TBL_PRODUTO (ID_PRODUTO,VALOR_PRODUTO,STATUS_PRODUTO,NOME_PRODUTO,DESCRICAO_PRODUTO,TAMANHO_PRODUTO,GENERO_PRODUTO) VALUES (ID_PRODUTO.NEXTVAL,81.30,1,'Vestido Fuxia','Sem descrição','G','F');
 
 ----------------------------------------------------
 
 INSERT INTO TBL_CONFIGURACOES(ID_CONF, MULTA_VALOR,CUPOM_VALOR) VALUES (ID_CONF.NEXTVAL,10.00,15.00);
 
 ----------------------------------------------------
 
 /* INSERT INTO TBL_CUPOM(ID_CUPOM, ID_CLIENTE,DATA_INCLUSAO,ID_OPERADOR, STATUS_CUPOM) 
 VALUES (ID_CUPOM.NEXTVAL,1,'11-04-2016',1,0);
     INSERT INTO TBL_CUPOM(ID_CUPOM, ID_CLIENTE,DATA_INCLUSAO,ID_OPERADOR, STATUS_CUPOM) 
 VALUES (ID_CUPOM.NEXTVAL,2,'20-04-2016',1,0);*/

  ----------------------------------------------------
  
   /*     INSERT INTO TBL_ALUGUEL (ID_ALUGUEL, ID_CLIENTE,ID_OPERADOR, ID_CONF,ID_CUPOM,DATA_ALUGUEL,DATA_PREVISTA,DATA_ENTREGA,STATUS_ALUGUEL,QUANTIDADE_MULTA,VALOR_ALUGUEL,VALOR_MULTA,VALOR_TOTAL) 
 VALUES (ID_ALUGUEL.NEXTVAL,1,1,1,null,'12-05-2016','16-05-2016',null,1,null,150.00,null,null);
   INSERT INTO TBL_ALUGUEL (ID_ALUGUEL, ID_CLIENTE,ID_OPERADOR, ID_CONF,ID_CUPOM,DATA_ALUGUEL,DATA_PREVISTA,DATA_ENTREGA,STATUS_ALUGUEL,QUANTIDADE_MULTA,VALOR_ALUGUEL,VALOR_MULTA,VALOR_TOTAL) 
 VALUES (ID_ALUGUEL.NEXTVAL,2,1,1,null,'12-05-2016','16-05-2016',null,1,null,150.00,null,null); */
 
 ----------------------------------------------------
 
/*        INSERT INTO TBL_PRODUTOS_ALUGUEL(ID_ALUGUEL, ID_PRODUTO) 
 VALUES (1,1);
      INSERT INTO TBL_PRODUTOS_ALUGUEL(ID_ALUGUEL, ID_PRODUTO) 
 VALUES (1,2); */
 
 ----------------------------------------------------
 
/*TRIGGER PARA LOG DE EDIÇÃO DE PRODUTO*/
 CREATE TABLE TBL_PRODUTO_ANTIGO (
  ID_PRODUTO_ANTIGO INTEGER NULL,
  VALOR_PRODUTO_ANTIGO FLOAT NULL,
  STATUS_PRODUTO_ANTIGO NUMBER(1) NULL,
  NOME_PRODUTO_ANTIGO VARCHAR2(60) NULL,
  DESCRICAO_PRODUTO_ANTIGO VARCHAR2(1000) NULL,
  TAMANHO_PRODUTO_ANTIGO VARCHAR2(20) NULL,
  GENERO_PRODUTO_ANTIGO VARCHAR2(1) NULL,
  DATA_ALTERACAO VARCHAR2(50) NULL
  );
  
CREATE INDEX INDEX_PRODUTO_ANTIGO ON TBL_PRODUTO_ANTIGO (ID_PRODUTO_ANTIGO); 

commit;


CREATE OR REPLACE TRIGGER HISTORICO_PRODUTO
BEFORE UPDATE ON TBL_PRODUTO
FOR EACH ROW
BEGIN
 INSERT INTO TBL_PRODUTO_ANTIGO (ID_PRODUTO_ANTIGO,VALOR_PRODUTO_ANTIGO,STATUS_PRODUTO_ANTIGO,NOME_PRODUTO_ANTIGO,DESCRICAO_PRODUTO_ANTIGO,TAMANHO_PRODUTO_ANTIGO,GENERO_PRODUTO_ANTIGO,DATA_ALTERACAO) VALUES (:NEW.ID_PRODUTO,:NEW.VALOR_PRODUTO,:NEW.STATUS_PRODUTO,:NEW.NOME_PRODUTO,:NEW.DESCRICAO_PRODUTO,:NEW.TAMANHO_PRODUTO,:NEW.GENERO_PRODUTO,(select to_char(sysdate,'DD/MM/YYYY HH24:MI:SS') from dual));
END;

 ----------------------------------------------------

/*PROCEDURE PARA INSERIR OS PRODUTOS NA TABELA PRODUTOS_ALUGUEL E MUDAR O STATUS PARA ALUGADO*/
create or replace PROCEDURE
PRODUTOS_ALUGUEL_INICIAR(idProduto IN NUMBER, idAluguel IN NUMBER) AS
BEGIN
                INSERT INTO TBL_PRODUTOS_ALUGUEL(ID_ALUGUEL, ID_PRODUTO, VALOR_PRODUTO_ALUGUEL, NOME_PRODUTO_ALUGUEL, DESCRICAO_PRODUTO_ALUGUEL, TAMANHO_PRODUTO_ALUGUEL, GENERO_PRODUTO_ALUGUEL)
                               VALUES (idAluguel, idProduto, (SELECT VALOR_PRODUTO FROM TBL_PRODUTO WHERE ID_PRODUTO = idProduto),(SELECT NOME_PRODUTO FROM TBL_PRODUTO WHERE ID_PRODUTO = idProduto),(SELECT DESCRICAO_PRODUTO FROM TBL_PRODUTO WHERE ID_PRODUTO = idProduto),(SELECT TAMANHO_PRODUTO FROM TBL_PRODUTO WHERE ID_PRODUTO = idProduto),(SELECT GENERO_PRODUTO FROM TBL_PRODUTO WHERE ID_PRODUTO = idProduto));
 
                UPDATE TBL_PRODUTO
                               SET STATUS_PRODUTO = 2
                               WHERE ID_PRODUTO=idProduto;
END PRODUTOS_ALUGUEL_INICIAR;

 ----------------------------------------------------
 
/*PROCEDURE PARA MUDAR O STATUS DO PRODUTO PARA ATIVO*/
CREATE OR REPLACE PROCEDURE
PRODUTOS_ALUGUEL_FINALIZAR(idProduto IN NUMBER) AS
BEGIN
                UPDATE TBL_PRODUTO
                               SET STATUS_PRODUTO = 1
                               WHERE ID_PRODUTO= idProduto;
 
END PRODUTOS_ALUGUEL_FINALIZAR;

 ----------------------------------------------------

/*PROCEDURE PARA FINALIZAR O ALUGUEL*/

create or replace PROCEDURE
FINALIZAR_ALUGUEL(idAluguel IN NUMBER, quantidadeMulta IN NUMBER) AS
BEGIN
 
                UPDATE TBL_ALUGUEL
                               SET STATUS_ALUGUEL = 2
                               WHERE ID_ALUGUEL=idAluguel;
               
                UPDATE TBL_ALUGUEL
                               SET QUANTIDADE_MULTA = quantidadeMulta
                               WHERE ID_ALUGUEL=idAluguel;
commit;
 
                UPDATE TBL_ALUGUEL
                               SET VALOR_MULTA = quantidadeMulta*(SELECT MULTA_VALOR FROM TBL_CONFIGURACOES WHERE ID_CONF = (SELECT ID_CONF FROM TBL_ALUGUEL WHERE ID_ALUGUEL = idAluguel)) 
                               WHERE ID_ALUGUEL=idAluguel;
commit;
                UPDATE TBL_ALUGUEL
                               SET DATA_ENTREGA = (select to_char(sysdate,'DD/MM/YYYY') from dual)
                               WHERE ID_ALUGUEL=idAluguel;

                UPDATE TBL_ALUGUEL
                               SET VALOR_TOTAL = (SELECT VALOR_ALUGUEL FROM TBL_ALUGUEL WHERE ID_ALUGUEL = idAluguel) + (SELECT VALOR_MULTA FROM TBL_ALUGUEL WHERE ID_ALUGUEL = idAluguel)
                               WHERE ID_ALUGUEL=idAluguel;
						
END FINALIZAR_ALUGUEL;

/*PROCEDURE PARA INSERIR CUPOM*/
CREATE OR REPLACE PROCEDURE
INSERIR_CUPOM(idCliente IN NUMBER, dataInclusao IN DATE, idOperador IN NUMBER) AS
BEGIN
                
				INSERT INTO TBL_CUPOM (ID_CUPOM, ID_CLIENTE, DATA_INCLUSAO, ID_OPERADOR, STATUS_CUPOM, VALOR_CUPOM)
							VALUES(ID_CUPOM.NEXTVAL, idCliente, dataInclusao, idOperador, 1, (SELECT CUPOM_VALOR FROM TBL_CONFIGURACOES WHERE ID_CONF = (SELECT MAX(ID_CONF) FROM TBL_CONFIGURACOES)));
 
END INSERIR_CUPOM;

commit;


 --COMANDO PARA APAGAR TUDO--
/*
BEGIN
  FOR i IN (SELECT us.sequence_name
			  FROM USER_SEQUENCES us) LOOP
	EXECUTE IMMEDIATE 'drop sequence '|| i.sequence_name ||'';
  END LOOP;
  FOR i IN (SELECT ut.table_name
			  FROM USER_TABLES ut) LOOP
	EXECUTE IMMEDIATE 'drop table '|| i.table_name ||' CASCADE CONSTRAINTS ';
  END LOOP;
END;
 */

  /*
  Site para gerar dados
http://www.generatedata.com/
*/
